name: Cypress Tests

on: [push]
jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    name: Run Cypress Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'  

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm test

      - name: Upload Cypress Screenshots and Videos
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/screenshots cypress/videos

  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Security Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'https://thinking-tester-contact-list.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

 name: API Tests
on:
  push:
    branches:
      - main

jobs:
  api_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.1 '

      - name: Install Dependencies
        run: npm install

      - name: Run API Tests
        run: npm run api:test

