name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    name: Run Cypress Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1  

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm test

      - name: Upload Cypress Screenshots and Videos
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/screenshots cypress/videos
 cypress_ui_tests:
    runs-on: ubuntu-latest
    name: Cypress UI Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress UI Tests
        run: npm run cypress:run

  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Security Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'https://thinking-tester-contact-list.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

  api_tests:
    runs-on: ubuntu-latest
    name: API Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run API Tests
        run: npm run api:test
