
name: ContactApp Workflow

on:
  push:
    branches:
      - main

jobs:
  cypress_ui_tests:
    runs-on: ubuntu-latest
    name: Cypress UI Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress UI Tests
        run: npm run cypress:run

  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Security Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'https://thinking-tester-contact-list.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

  
